#ifndef VIRTUALKEYBOARD_GLOBAL_H
#define VIRTUALKEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIRTUALKEYBOARD_LIBRARY)
#  define VIRTUALKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIRTUALKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIRTUALKEYBOARD_GLOBAL_H
